# Generated by Django 4.2 on 2023-04-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
